version: '2'
services:
  webserver:
    build: .docker/webserver
    links:
      - php-fpm
    ports:
      - "5000:80"
    volumes:
      - ./:/var/www/html
  php-fpm:
    build: .docker/php-fpm
    expose:
      - 9000
    links:
      - redis
    volumes:
      - ./:/var/www/html
  worker:
    build: .docker/worker
    links:
      - redis
      - php-fpm
  redis:
    image: sameersbn/redis
    restart: always
    expose:
      - "6379"